/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package konyvtar;

import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;



/**
 *
 * @author Gergő
 */
public class Gui extends javax.swing.JFrame {
    /** Creates new form Gui */
    private User user=new User();
    protected Login loginWindow=new Login();
    
    public Gui() {
        initComponents();
    }
    
    public boolean checkLogin(){
        if(!user.loginValue()){
            this.setVisible(false);
            loginWindow.setVisible(true);
            return true;
        }else{
            setDisplayName(user.getUsername());
        }
        return false;
    }

    protected void returnLogin(int id){
        this.setVisible(true);
        user.setLogin(true);
        user.setId(id);
        setDisplayName(user.getUsername());
    }
    
    private void setDisplayName(String newName){
        displayName.setText(newName);
    }
    
    private void logout(){
        user.setLogin(false);
        checkLogin();
    }
    
    private void switchPanel(javax.swing.JPanel panel){
        mainPanel.removeAll();
        mainPanel.add(panel);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MenuPanel = new javax.swing.JPanel();
        displayName = new javax.swing.JLabel();
        borrowButton = new javax.swing.JButton();
        newBookButton = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        mainPanel = new javax.swing.JLayeredPane();
        borrow = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        CardNumber = new javax.swing.JTextField();
        borrowStockNum = new javax.swing.JTextField();
        UpBorrow = new javax.swing.JButton();
        scannerCardBorrow = new javax.swing.JToggleButton();
        scannerISBNborrow = new javax.swing.JToggleButton();
        jLabel6 = new javax.swing.JLabel();
        borrowDate = new com.toedter.calendar.JDateChooser();
        uploadBook = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        bookISBNnew = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        scannerISBNupload = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Main");

        MenuPanel.setBackground(new java.awt.Color(51, 153, 255));

        displayName.setText("jLabel1");

        borrowButton.setText("Kölcsönzés");
        borrowButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrowButtonActionPerformed(evt);
            }
        });

        newBookButton.setText("Új Könyv");
        newBookButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newBookButtonActionPerformed(evt);
            }
        });

        jButton3.setText("jButton3");

        jButton4.setText("Kijelentkezés");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MenuPanelLayout = new javax.swing.GroupLayout(MenuPanel);
        MenuPanel.setLayout(MenuPanelLayout);
        MenuPanelLayout.setHorizontalGroup(
            MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(displayName, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(borrowButton, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(newBookButton, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );
        MenuPanelLayout.setVerticalGroup(
            MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MenuPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(displayName)
                    .addComponent(borrowButton)
                    .addComponent(newBookButton)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addContainerGap())
        );

        jLabel1.setText("Kártya azonosító:");

        jLabel2.setText("Könyv Azonosító:");

        CardNumber.setText("kártyaszám");

        borrowStockNum.setText("könyvtári szám");

        UpBorrow.setText("Küldés");
        UpBorrow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpBorrowActionPerformed(evt);
            }
        });

        scannerCardBorrow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scannerCardBorrowActionPerformed(evt);
            }
        });

        scannerISBNborrow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scannerISBNborrowActionPerformed(evt);
            }
        });

        jLabel6.setText("Visszahozás Dátuma:");

        borrowDate.setMinSelectableDate(new Date(System.currentTimeMillis()));

        javax.swing.GroupLayout borrowLayout = new javax.swing.GroupLayout(borrow);
        borrow.setLayout(borrowLayout);
        borrowLayout.setHorizontalGroup(
            borrowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(borrowLayout.createSequentialGroup()
                .addGroup(borrowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(borrowLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(UpBorrow))
                    .addGroup(borrowLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(borrowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(borrowLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(borrowDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(borrowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(borrowLayout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addGap(18, 18, 18)
                                    .addComponent(borrowStockNum))
                                .addGroup(borrowLayout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addGap(18, 18, 18)
                                    .addComponent(CardNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(borrowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(scannerCardBorrow)
                            .addComponent(scannerISBNborrow))))
                .addContainerGap(384, Short.MAX_VALUE))
        );
        borrowLayout.setVerticalGroup(
            borrowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(borrowLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(borrowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(CardNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(scannerCardBorrow, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(borrowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(borrowStockNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(scannerISBNborrow, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(borrowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(borrowDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 110, Short.MAX_VALUE)
                .addComponent(UpBorrow)
                .addContainerGap())
        );

        jLabel3.setText("Iró");

        jLabel4.setText("Cím");

        jLabel5.setText("ISBN");

        jTextField1.setText("jTextField1");

        jTextField2.setText("jTextField2");

        bookISBNnew.setText("jTextField3");

        jButton2.setText("Küldés");

        scannerISBNupload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scannerISBNuploadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout uploadBookLayout = new javax.swing.GroupLayout(uploadBook);
        uploadBook.setLayout(uploadBookLayout);
        uploadBookLayout.setHorizontalGroup(
            uploadBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(uploadBookLayout.createSequentialGroup()
                .addGroup(uploadBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(uploadBookLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(uploadBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(uploadBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(bookISBNnew, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                            .addComponent(jTextField2)
                            .addComponent(jTextField1))
                        .addGap(18, 18, 18)
                        .addComponent(scannerISBNupload))
                    .addGroup(uploadBookLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton2)))
                .addContainerGap(488, Short.MAX_VALUE))
        );
        uploadBookLayout.setVerticalGroup(
            uploadBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(uploadBookLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(uploadBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(uploadBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(uploadBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(bookISBNnew, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(scannerISBNupload, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addContainerGap())
        );

        mainPanel.setLayer(borrow, javax.swing.JLayeredPane.DEFAULT_LAYER);
        mainPanel.setLayer(uploadBook, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(borrow, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(uploadBook, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(borrow, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(uploadBook, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MenuPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainPanel)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(MenuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mainPanel)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        logout();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void borrowButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrowButtonActionPerformed
        switchPanel(borrow);
    }//GEN-LAST:event_borrowButtonActionPerformed

    private void newBookButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newBookButtonActionPerformed
        switchPanel(uploadBook);
    }//GEN-LAST:event_newBookButtonActionPerformed

    private void scannerCardBorrowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scannerCardBorrowActionPerformed
        if(scannerCardBorrow.isSelected()){
            CardNumber.setText(JOptionPane.showInputDialog(""));
            scannerCardBorrow.setSelected(false);
        }
    }//GEN-LAST:event_scannerCardBorrowActionPerformed

    private void scannerISBNborrowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scannerISBNborrowActionPerformed
        if(scannerISBNborrow.isSelected()){
            borrowStockNum.setText(JOptionPane.showInputDialog(""));
            scannerISBNborrow.setSelected(false);
        }
    }//GEN-LAST:event_scannerISBNborrowActionPerformed

    private void scannerISBNuploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scannerISBNuploadActionPerformed
        if(scannerISBNupload.isSelected()){
            bookISBNnew.setText(JOptionPane.showInputDialog(""));
            scannerISBNupload.setSelected(false);
        }
    }//GEN-LAST:event_scannerISBNuploadActionPerformed

    private void UpBorrowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpBorrowActionPerformed
        if(CardNumber.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Nem adtál meg kártya számot!","Error",JOptionPane.ERROR_MESSAGE);
            return;
        }
        if(borrowStockNum.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Nem adtál meg könyv azonosítót!","Error",JOptionPane.ERROR_MESSAGE);
            return;
        }
        if(borrowDate.getDate()==null){
            JOptionPane.showMessageDialog(rootPane, "Nem adtál visszahozási dátumot!","Error",JOptionPane.ERROR_MESSAGE);
            return;
        }
        dbConnect db=new dbConnect();
        ResultSet result = db.getResult("Select id from cards Where id=\""+CardNumber.getText()+"\"");
        try{
            if(!result.next()){
                JOptionPane.showMessageDialog(rootPane, "Hibás kártyaszám!","Error",JOptionPane.ERROR_MESSAGE);
                return;
            }
            result = db.getResult("Select stockNum from stock Where stockNum=\""+borrowStockNum.getText()+"\"");
            if(!result.next()){
                JOptionPane.showMessageDialog(rootPane, "Hibás könyv azonosító!","Error",JOptionPane.ERROR_MESSAGE);
                return;
            }
            result = db.getResult("Select id from borrow where stockNum=\""+borrowStockNum.getText()+"\" and state=0");
            if(result.next()){
                JOptionPane.showMessageDialog(rootPane, "Hiba ezt a könyvet nem hozták vissza határidőre!","Error",JOptionPane.ERROR_MESSAGE);
                return;
            }
            SimpleDateFormat sd=new SimpleDateFormat("yyyy-MM-dd");
            
            if (db.insertToSql("borrow(cardNum,stockNum,date,state)", String.format("VALUES( %s,%s,'%s',0 )",CardNumber.getText(),borrowStockNum.getText(),String.valueOf(sd.format(borrowDate.getDate()))))){
                JOptionPane.showMessageDialog(rootPane, "Sikeres kölcsönzés!","Info",JOptionPane.INFORMATION_MESSAGE);
                CardNumber.setText("kártyaszám");
                borrowStockNum.setText("könyvtári szám");
                borrowDate.setDate(null);
            }
            
            
        }catch(Exception e){
            System.err.println(e.getMessage());
            JOptionPane.showMessageDialog(rootPane, "SQL error Kérlek próbáld újra késöbb!","Error",JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_UpBorrowActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CardNumber;
    private javax.swing.JPanel MenuPanel;
    private javax.swing.JButton UpBorrow;
    private javax.swing.JTextField bookISBNnew;
    private javax.swing.JPanel borrow;
    private javax.swing.JButton borrowButton;
    private com.toedter.calendar.JDateChooser borrowDate;
    private javax.swing.JTextField borrowStockNum;
    private javax.swing.JLabel displayName;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLayeredPane mainPanel;
    private javax.swing.JButton newBookButton;
    private javax.swing.JToggleButton scannerCardBorrow;
    private javax.swing.JToggleButton scannerISBNborrow;
    private javax.swing.JToggleButton scannerISBNupload;
    private javax.swing.JPanel uploadBook;
    // End of variables declaration//GEN-END:variables

}
